---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - ^saludar_a\s*\(\s*\"Juli\"\s*\,\s*18\s*\)\s*$
  - ^saludar_a\s*\(\s*\"Pun Pun\"\s*\,\s*19\s*\)\s*$
name: Hora de tomar una decisión
